export const agentReviewJsonSchema = {
  type: "object",
  required: [
    "agentName",
    "agentType",
    "variantId",
    "attention",
    "clarity",
    "trust",
    "conversionIntent",
    "fatigueRisk",
    "recommendation",
    "topPositive",
    "topConcern",
    "suggestedEdit",
    "reasoning",
    "evidenceRefs",
  ],
  properties: {
    agentName: { type: "string" },
    agentType: { type: "string", enum: ["specialist", "persona"] },
    variantId: { type: "string" },
    attention: { type: "number", minimum: 0, maximum: 10 },
    clarity: { type: "number", minimum: 0, maximum: 10 },
    trust: { type: "number", minimum: 0, maximum: 10 },
    conversionIntent: { type: "number", minimum: 0, maximum: 10 },
    fatigueRisk: { type: "string", enum: ["low", "medium", "high"] },
    recommendation: { type: "string", enum: ["scale", "test", "edit", "pivot", "pause"] },
    topPositive: { type: "string" },
    topConcern: { type: "string" },
    suggestedEdit: { type: "string" },
    reasoning: { type: "string" },
    evidenceRefs: {
      type: "array",
      items: { type: "string" },
    },
  },
};

export const finalReportJsonSchema = {
  type: "object",
  required: [
    "winner",
    "executiveSummary",
    "ranking",
    "champion",
    "whyItWins",
    "risks",
    "whatToDoNext",
    "abTestPlan",
  ],
  properties: {
    winner: { type: "string" },
    executiveSummary: { type: "string" },
    ranking: {
      type: "array",
      items: {
        type: "object",
        required: [
          "variantId",
          "rank",
          "score",
          "predictedOutcome",
          "creativeHealth",
          "swarmConfidence",
          "action",
          "topReasons",
          "risks",
          "recommendedEdits",
        ],
        properties: {
          variantId: { type: "string" },
          rank: { type: "number" },
          score: { type: "number", minimum: 0, maximum: 100 },
          predictedOutcome: { type: "string" },
          creativeHealth: { type: "number", minimum: 0, maximum: 100 },
          swarmConfidence: { type: "string", enum: ["low", "medium", "high"] },
          action: { type: "string", enum: ["scale", "test", "edit", "pivot", "pause"] },
          topReasons: { type: "array", items: { type: "string" } },
          risks: { type: "array", items: { type: "string" } },
          recommendedEdits: { type: "array", items: { type: "string" } },
        },
      },
    },
    champion: { type: "string" },
    whyItWins: { type: "array", items: { type: "string" } },
    risks: { type: "array", items: { type: "string" } },
    whatToDoNext: { type: "array", items: { type: "string" } },
    abTestPlan: {
      type: "object",
      required: [
        "primaryMetric",
        "secondaryMetric",
        "control",
        "challenger",
        "trafficSplit",
        "hypothesis",
        "stopCondition",
        "actionIfWinner",
        "actionIfLoser",
      ],
      properties: {
        primaryMetric: { type: "string" },
        secondaryMetric: { type: "string" },
        control: { type: "string" },
        challenger: { type: "string" },
        trafficSplit: { type: "string" },
        hypothesis: { type: "string" },
        stopCondition: { type: "string" },
        actionIfWinner: { type: "string" },
        actionIfLoser: { type: "string" },
      },
    },
  },
};

export const visionFeaturesJsonSchema = {
  type: "object",
  required: [
    "ocrText",
    "ctaText",
    "headline",
    "subhead",
    "dominantColors",
    "textDensity",
    "visualClutter",
    "readabilityScore",
    "brandVisibilityScore",
    "noveltyScore",
    "facesCount",
    "productCount",
    "hasLogo",
    "hasPerson",
    "hasPrice",
    "hasReward",
    "hasGameplay",
    "hasUgcStyle",
    "layoutJson",
  ],
  properties: {
    ocrText: { type: "string" },
    ctaText: { type: "string" },
    headline: { type: "string" },
    subhead: { type: "string" },
    dominantColors: { type: "array", items: { type: "string" } },
    textDensity: { type: "number", minimum: 0, maximum: 1 },
    visualClutter: { type: "number", minimum: 0, maximum: 1 },
    readabilityScore: { type: "number", minimum: 0, maximum: 1 },
    brandVisibilityScore: { type: "number", minimum: 0, maximum: 1 },
    noveltyScore: { type: "number", minimum: 0, maximum: 1 },
    facesCount: { type: "number", minimum: 0 },
    productCount: { type: "number", minimum: 0 },
    hasLogo: { type: "boolean" },
    hasPerson: { type: "boolean" },
    hasPrice: { type: "boolean" },
    hasReward: { type: "boolean" },
    hasGameplay: { type: "boolean" },
    hasUgcStyle: { type: "boolean" },
    layoutJson: {
      type: "object",
      additionalProperties: true,
    },
  },
};

export const copilotAnswerJsonSchema = {
  type: "object",
  required: ["answer", "citedVariantIds", "nextAction"],
  properties: {
    answer: { type: "string" },
    citedVariantIds: {
      type: "array",
      items: { type: "string" },
    },
    nextAction: { type: "string" },
  },
};
